### ISSUE TITLE
一日で回復するスタミナを得る

### ISSUE THREAD

**Issue by kunosu** [kusakawab/round_calculater#2]
## 理由

アイテムを使わずに周回した場合、ほしいイベポを得るのに必要な日数を得るために必要

## タスク

- [x] 単体テスト
- [x] 関数

## 計算式

- 1スタミナ回復するのにかかる時間 = x(分)
- 一日で回復するスタミナ = 回復間隔 =(24 * 60) / x

**Comment by kusakawab** [comment]
1スタミナ回復するのにかかる時間=回復間隔

**Comment by kusakawab** [comment]
a87d5cca793fb6e4280889bc4ef4d5a9d99c08cd でマージ完了

**Comment by kunosu** [comment]
a87d5cca793fb6e4280889bc4ef4d5a9d99c08cd でマージ完了
